name: R8AM
favicon: null
layout_spectrum: 0.62626
typography_spectrum: 0
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8d4b9'
    - '#0e2431'
    - '#fc3a52'
    - '#707070'
    - '#9e9e9e'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
