typography_spectrum: 0
color:
  brandColors:
    - '#e8d4b9'
    - '#0e2431'
    - '#fc3a52'
    - '#707070'
    - '#9e9e9e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.79647
analytics:
  google: null
  facebook: '506767772843593'
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
name: R8AM
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Reporte 8AM
purpose: []
