layout_spectrum: 0.73702
favicon: null
name: R8AM
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
  brandColors:
    - '#000000'
    - '#ff0017'
    - '#490005'
    - '#b8000f'
    - '#700007'
typography_spectrum: 0.7212
