layout_spectrum: 0.0885156610590581
typography_spectrum: 0.2042775111378973
color:
  saturation: 0.9156245578452945
  brandStrength: 0.400378486382231
  lightness: 0.28510156471835507
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  rhythmicContrast: 0.5498735831221474
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
author:
  name: Pablo Antonio Cicero Alonzo
  email: cicero.pablo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc4df248-8b5a-4e9d-8282-66d1811873cc.jpg
name: 8AM
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4625151f-1124-4432-914d-1b8a94a08ead.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: REPORTE 8AM
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/71a8a016-5905-4011-9131-36203491aa4b.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/71a8a016-5905-4011-9131-36203491aa4b.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/71a8a016-5905-4011-9131-36203491aa4b.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/71a8a016-5905-4011-9131-36203491aa4b.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
  - type: internal
    label: ¿Quién soy?
    item: 4af21691-de7e-4702-a20e-f9d5e4f1320a
