name: R8AM
favicon: null
layout_spectrum: 0.85387
typography_spectrum: 0.04734
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9ab84'
    - '#000000'
    - '#e7ebb0'
    - '#8b8c6c'
    - '#4b4c3c'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
