typography_spectrum: 0.6781454653288285
color:
  saturation: 0.859845136194536
  brandStrength: 0.2612486813276416
  lightness: 0.41900045599521013
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#A9A9A9'
    - '#7C7C7C'
    - '#525252'
  rhythmicContrast: 0.991829590496266
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c481c112-a804-46b7-92a8-67878132ce2d.png
name: R8AM
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Una historia trágica
    url: >-
      https://thegrid.ai/por-entregas/todo-lo-que-se-describe-en-este-relato-sucedio-en-realidad
    type: external
  - name: Sígueme en redes sociales
    url: 'https://twitter.com/PabloCicero'
    type: external
  - name: Reporte 6PM
    url: 'http://thegrid.ai/6pm/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b80ee182-7ec7-4cb7-9315-c864be2fd5e7.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: R8AM
content: []
description: Por Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
