layout_spectrum: 0.85387
favicon: null
name: R8AM
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  saturation: 0
  brandColors:
    - '#d27d39'
    - '#2e0202'
    - '#cf592f'
    - '#ebad4c'
    - '#ffffff'
  lightness: 0.5625
  rhythmicContrast: 1
typography_spectrum: 1
