name: R8AM
favicon: null
layout_spectrum: 0.79647
typography_spectrum: 0.05632
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Reporte 8AM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: '506767772843593'
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#026069'
    - '#9c0000'
    - '#e85914'
    - '#299fa5'
    - '#ebf479'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
