title: Reporte 8AM
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Por Pablo A. Cicero Alonzo
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#1a1a1a'
    - '#4a4a4a'
    - '#bcbcbc'
    - '#e6e6e6'
    - '#ffffff'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: '506767772843593'
name: R8AM
favicon: null
navigation:
  - name: Contacto
    url: 'http://8am.com.mx/'
    type: external
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
typography_spectrum: 0.2723404
layout_spectrum: 0.4914894
