layout_spectrum: 0.6531915
favicon: null
name: R8AM
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.3340425
  saturation: 0
  rhythmicContrast: 1
  brandColors:
    - '#003399'
    - '#FE0000'
    - '#00184A'
    - '#E70815'
    - '#792569'
typography_spectrum: 0.2148936
