name: R8AM
favicon: null
layout_spectrum: 0.00898
typography_spectrum: 0.63682
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
navigation:
  - name: Contacto
    url: 'http://8am.com.mx/'
    type: external
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Reporte 8AM
description: Por Pablo A. Cicero Alonzo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: '506767772843593'
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#4a4a4a'
    - '#bcbcbc'
    - '#e6e6e6'
    - '#ffffff'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
