name: R8AM
favicon: null
layout_spectrum: 0.4795863756444305
typography_spectrum: 0.016331878257915378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5060274070128798
  lightness: 0.6752961610909551
  saturation: 0.6714387778192759
  rhythmicContrast: 0.11367570562288165
purpose: []
