layout_spectrum: 0.21651644073694132
typography_spectrum: 0.63937206539934
color:
  saturation: 0.2348737243408024
  brandStrength: 0.6587368156885415
  lightness: 0.17684621619835203
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#A9A9A9'
    - '#7C7C7C'
    - '#525252'
  rhythmicContrast: 0.018564555851539762
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
author:
  name: Pablo Antonio Cicero Alonzo
  email: cicero.pablo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c481c112-a804-46b7-92a8-67878132ce2d.png
name: 8AM
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Una historia trágica
    url: >-
      https://thegrid.ai/por-entregas/todo-lo-que-se-describe-en-este-relato-sucedio-en-realidad
    type: external
  - name: Reporte 6PM
    url: 'http://thegrid.ai/6pm/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: REPORTE 8AM
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d94b141-1dda-4449-9b1d-9b8c28306204.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d94b141-1dda-4449-9b1d-9b8c28306204.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
  - type: internal
    label: ¿Quién soy?
    item: 4af21691-de7e-4702-a20e-f9d5e4f1320a
