name: R8AM
favicon: null
layout_spectrum: 0.73702
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#012345'
    - '#123456'
    - '#345678'
    - '#456789'
    - '#234567'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
