name: R8AM
favicon: null
layout_spectrum: 0.79157
typography_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Reporte 8AM
navigation:
  - id: 'http://8am.com.mx/'
    url: 'http://8am.com.mx/'
    name: Contacto
    type: external
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: '506767772843593'
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#d0d0d0'
    - '#363636'
    - '#7f7f7f'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
