layout_spectrum: 0.4857728825307608
typography_spectrum: 0.5930294114511718
color:
  saturation: 0.24038553799714635
  brandStrength: 0.7854330960547755
  lightness: 0.9304827096611078
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.8932550642695647
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
author:
  name: Pablo Antonio Cicero Alonzo
  email: cicero.pablo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45c4ac6a-37d5-4e74-81b2-29c75b737ce8.png
name: 8AM
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/67c40601-20e6-49f5-b98c-492dc6a4f5b2.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: REPORTE 8AM
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FFD7w2l88dl8%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFD7w2l88dl8&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FFD7w2l88dl8%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Andrew P. Alderete
          url: 'https://www.youtube.com/user/aaldere1'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - se7en
        - credits
        - intro
      description: >-
        Intro credits to the film, Se7en. Wonderfully shot, and you can clearly
        get the tone of the film before any of the action is shot.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=FD7w2l88dl8&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=FD7w2l88dl8&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=FD7w2l88dl8&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=FD7w2l88dl8&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=FD7w2l88dl8&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=FD7w2l88dl8'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=FD7w2l88dl8
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=FD7w2l88dl8
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/FD7w2l88dl8'
      title: Se7en Intro Credits
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
  - type: internal
    label: ¿Quién soy?
    item: 4af21691-de7e-4702-a20e-f9d5e4f1320a
