layout_spectrum: 0.9203799584689597
typography_spectrum: 0.8946002651255873
color:
  saturation: 0.3789155083872599
  brandStrength: 0.24038570571358842
  lightness: 0.4465008617066179
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.2361176176630145
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bff5f7d8-dbba-482c-8677-87503d2dd89d.png
name: R8AM
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Una historia trágica
    url: >-
      https://thegrid.ai/por-entregas/todo-lo-que-se-describe-en-este-relato-sucedio-en-realidad
    type: external
  - name: Sígueme en redes sociales
    url: 'https://twitter.com/PabloCicero'
    type: external
  - name: Reporte 6PM
    url: 'http://thegrid.ai/6pm/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc931bc3-77ee-4dce-bde9-990b1bc5d87f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Reporte 8AM
content: []
description: Por Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
