name: R8AM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1106383
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0018'
    - '#0820f4'
    - '#f17f2f'
    - '#9aa1ed'
  brandStrength: 1
  lightness: 0.3340425
  saturation: 0
  rhythmicContrast: 1
purpose: []
