layout_spectrum: 0.4857728825307608
typography_spectrum: 0.5930294114511718
color:
  saturation: 0.24038553799714635
  brandStrength: 0.7854330960547755
  lightness: 0.9304827096611078
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.8932550642695647
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-18458867-3
  facebook: '506767772843593'
author:
  name: Pablo Antonio Cicero Alonzo
  email: cicero.pablo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45c4ac6a-37d5-4e74-81b2-29c75b737ce8.png
name: 8AM
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/67c40601-20e6-49f5-b98c-492dc6a4f5b2.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: REPORTE 8AM
content: []
description: Pablo A. Cicero Alonzo
purpose:
  - type: contact
    url: 'mailto:pcicero@8am.com.mx'
    label: Escríbeme
  - type: internal
    label: ¿Quién soy?
    item: 4af21691-de7e-4702-a20e-f9d5e4f1320a
