name: R8AM
favicon: null
layout_spectrum: 0.62925
typography_spectrum: 0.42517
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0000ff'
    - '#ff0000'
    - '#ffff00'
    - '#0000ff'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
