title: Reporte 8AM
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: CICERO
color:
  saturation: 0.9340426
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#0541FB'
    - '#FF003F'
    - '#5303E6'
    - '#FDAA07'
    - '#811701'
  rhythmicContrast: 0.5
navigation:
  - name: Contacto
    url: 'http://8am.com.mx/'
    type: external
analytics:
  twitter: null
  google: null
  facebook: '506767772843593'
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: R8AM
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e07bbdcb-7da6-458c-9167-ff260ff046b6.jpg
typography_spectrum: 0.63682
layout_spectrum: 0.5255319
