name: R8AM
favicon: null
layout_spectrum: 0.74556
typography_spectrum: 0.1106383
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3d3d3'
    - '#000000'
    - '#808080'
    - '#2f2f2f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
